name: Run get_data.py Script

on: 
  push:
    branches:
      - main  # Specify the branch you want this to trigger on (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pymongo

    # Run the Python script
    - name: Execute get_data.py
      env:  # Provide environment variables here
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        MONGO_URL: ${{ secrets.MONGO_URL }}
      run: |
        python get_data.py
