name: Run get_data.py Script

on: [push]
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pymongo

    # Set up environment variables
    - name: Set Environment Variables
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        MONGO_URL: ${{ secrets.MONGO_URL }}

    # Run the Python script
    - name: Execute get_data.py
      run: python get_data.py
